# PR to dev/main, run tests and create review
name: Deploy Production
on:
  push:
    branches:
      - development
      - sellerScan

jobs:
  ci-test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        node: [14]

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}

      - name: Gen Token
        run: |
          echo "//npm.pkg.github.com/:_authToken=${{ secrets.NPM_TOKEN }}" > ~/.npmrc
  review:
    needs: [ci-test]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [ubuntu-latest]
        node: [14]

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
      # - uses: expo/expo-github-action@v6
      #   with:
      #     expo-version: 4.x
      #     token: ${{ secrets.EXPO_TOKEN }}
      # expo-username: "niejianlong@cavalry.online"
      # expo-password: "NJLd123456"
      - name: ðŸ— Setup Expo and EAS
        uses: expo/expo-github-action@v7
        with:
          expo-version: latest
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}

      - name: Install
        run: yarn install

      - name: Gen Graphql
        run: yarn gen:gql

      - name: Expo Publish
        run: |
          eas build -p ios --non-interactive --json

      - name: Expo Publish
        run: |
          eas build -p android --non-interactive --json > buildLogAndroid.json
          sed -i 's/\[//g' buildLogAndroid.json
          sed -i 's/\]//g' buildLogAndroid.json
          cat buildLogAndroid.json

      - name: Parse Asset URL
        id: androidUrl
        run: |
          result=$(cat buildLogAndroid.json  | sed 's/,/\n/g' | grep 'buildUrl' | sed 's/"buildUrl": "//g' | sed 's/"//g' | sed -e 's/^[ ]*//g' | sed -e 's/[ ]*$//g')
          echo "::set-output name=releaseChannel::$result"

      # - name: Parse Asset URL
      #   id: androidUrl
      #   uses: sergeysova/jq-action@v2
      #   with:
      #     cmd: "jq .artifacts buildLogAndroid.json -r"

      # run: |
      #   ASSET_URL=$(cat buildLogAndroid.txt | tail | egrep -o 'https?://expo\.io/artifacts/[^ ]+')
      #   echo The android url is $ASSET_URL
      #   echo "::set-output name=assetUrl::$ASSET_URL"

      - uses: actions/checkout@v2
      - name: Slack Notification
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_LINK_NAMES: true
          SLACK_ICON: https://raw.githubusercontent.com/zhuchuanwu/publicImage/main/production.png
          SLACK_FOOTER: ${{ steps.androidUrl.outputs.releaseChannel }}

          SLACK_TITLE: Salami Slicing Updated -- Production
          SLACK_USERNAME: Salami Slicing

      - name: Echo Parse Asset URL
        run: echo ${{ steps.androidUrl.outputs.releaseChannel }}

      # - name: Find Comment
      #   uses: peter-evans/find-comment@v1
      #   id: fc
      #   with:
      #     # issue-number: ${{ github.event.pull_request.number }}
      #     issue-number: 1
      #     comment-author: "github-actions[bot]"
      #     body-includes: This is a QR code for access to the preview app.

      # - name: Comment Review QR code
      #   # if: steps.fc.outputs.comment-id == ''
      #   uses: peter-evans/create-or-update-comment@v1
      #   with:
      #     # issue-number: ${{ github.event.pull_request.number }}
      #     issue-number: 2
      #     body: |
      #       :lock: This is a QR code for access to the preview app.
      #       :iphone: Scan a code with your device.
      #       ![QR Code](https://api.qrserver.com/v1/create-qr-code/?size=200x200&data=https://expo.dev/@the-pique-lab/frontend-parent?release-channel=staging-v1)
      #     reactions: rocket
  # slackNotification:
  #   needs: [review]
  #   runs-on: ubuntu-latest
  #   steps:
